import 'package:flutter/material.dart';

import '../../../../app/theme/app_theme.dart';
import '../../../../core/filters/filter_preset.dart';
import '../../../../core/filters/filtered_view.dart';

/// The horizontal strip of looks.
///
/// Each swatch is the preset applied to one shared reference gradient, so the
/// thumbnails are generated by the same code path that grades the preview — a
/// recipe cannot be tweaked and leave its thumbnail behind. It also costs nothing:
/// no extra camera textures, no snapshots.
class FilterTray extends StatelessWidget {
  const FilterTray({
    super.key,
    required this.presets,
    required this.selected,
    required this.onSelected,
  });

  final List<FilterPreset> presets;
  final FilterPreset selected;
  final ValueChanged<FilterPreset> onSelected;

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      height: 96,
      child: ListView.separated(
        scrollDirection: Axis.horizontal,
        padding: const EdgeInsets.symmetric(horizontal: 16),
        itemCount: presets.length,
        separatorBuilder: (_, _) => const SizedBox(width: 12),
        itemBuilder: (BuildContext context, int index) {
          final FilterPreset preset = presets[index];
          return _FilterSwatch(
            preset: preset,
            isSelected: preset == selected,
            onTap: () => onSelected(preset),
          );
        },
      ),
    );
  }
}

class _FilterSwatch extends StatelessWidget {
  const _FilterSwatch({
    required this.preset,
    required this.isSelected,
    required this.onTap,
  });

  final FilterPreset preset;
  final bool isSelected;
  final VoidCallback onTap;

  static const double _size = 58;

  @override
  Widget build(BuildContext context) {
    return Semantics(
      button: true,
      selected: isSelected,
      label: '${preset.label} filter',
      child: GestureDetector(
        onTap: onTap,
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: <Widget>[
            AnimatedContainer(
              duration: AppTheme.quickTransition,
              curve: Curves.easeOut,
              width: _size,
              height: _size,
              padding: const EdgeInsets.all(2.5),
              decoration: BoxDecoration(
                borderRadius: BorderRadius.circular(14),
                border: Border.all(
                  color: isSelected ? AppColors.accent : Colors.transparent,
                  width: 2.5,
                ),
              ),
              child: ClipRRect(
                borderRadius: BorderRadius.circular(9),
                child: FilteredView(preset: preset, child: const _ReferenceGradient()),
              ),
            ),
            const SizedBox(height: 6),
            Text(
              preset.label,
              style: TextStyle(
                color: isSelected ? AppColors.onDark : AppColors.onDarkMuted,
                fontSize: 11,
                fontWeight: isSelected ? FontWeight.w700 : FontWeight.w500,
                shadows: const <Shadow>[Shadow(color: Colors.black54, blurRadius: 4)],
              ),
            ),
          ],
        ),
      ),
    );
  }
}

/// The image every swatch grades.
///
/// The stops are chosen so each kind of adjustment is visible: a skin tone for the
/// beauty and warmth looks, a saturated blue and green for saturation and
/// temperature shifts, and near-white and near-black ends so contrast changes
/// show up.
class _ReferenceGradient extends StatelessWidget {
  const _ReferenceGradient();

  @override
  Widget build(BuildContext context) {
    return const DecoratedBox(
      decoration: BoxDecoration(
        gradient: LinearGradient(
          begin: Alignment.topLeft,
          end: Alignment.bottomRight,
          colors: <Color>[
            Color(0xFFF7E6D5),
            Color(0xFFE9A178),
            Color(0xFFD1503F),
            Color(0xFF3C6FD1),
            Color(0xFF2E9E63),
            Color(0xFF161418),
          ],
          stops: <double>[0.0, 0.2, 0.4, 0.62, 0.82, 1.0],
        ),
      ),
      child: SizedBox.expand(),
    );
  }
}
